language: python

python:
#  - "3.3"
  - "2.7"
  - "2.6"

env:
#  - DJANGO_VERSION="1.7.*"
  - DJANGO_VERSION="1.8.*"

install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install -q -r requirements.txt --use-mirrors
  - pip install -q -r requirements-test.txt --use-mirrors
  - pip install -q pep8 --use-mirrors

branches:
 only:
  - master

script:
  - django-admin.py test sponsors --settings=sponsors.tests.settings
  - python manage.py test sponsors --settings=sponsors.app_settings
  - coverage run --source sponsors runtests.py --settings=sponsors.app_settings
  - coverage run manage.py test sponsors
  - coverage run manage.py test sponsors --settings=sponsors.app_settings


# report coverage to coveralls.io
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls