language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION="1.6"
  - DJANGO_VERSION="1.7"
  - DJANGO_VERSION="1.8"

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION="1.7"
#    - python: "2.6"
#      env: DJANGO_VERSION="1.8"

install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install -q -r requirements.txt --use-mirrors
  - pip install -q -r requirements-test.txt --use-mirrors
  - pip install -q pep8 --use-mirrors
  - export PYTHONPATH=.

branches:
 only:
  - master

script:
  - coverage run --source sponsors runtests.py sponsors


# report coverage to coveralls.io
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls